services:
  frontend:
    image: watermelon/frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:80
    develop:
      watch:
        - path: ./src/
          target: /var/www/html/
          action: sync
